substitutions:
  node_name: configuredtrainsounds
  friendly_name: "Configured Train Sounds"
  area: Dev
  comment: "This is a version that has wifi pre-configured as a secret"
  box_config_file_name: configured_train_sounds
  onboard_light_id: "atom_light"
  train_sounds_script_mode: restart
  # FIXME: make this dynamic
  first_train_sound_url: "https://www.soundjay.com/transportation/train-crossing-bell-01.mp3"
  second_train_sound_url: "https://www.soundjay.com/transportation/train-depart-with-whistle-01.mp3"
  third_train_sound_url: "https://www.soundjay.com/transportation/train-pass-by-with-whistle-01.mp3"
  fourth_train_sound_url: "https://www.soundjay.com/transportation/train-whistle-01.mp3"

packages:
  # logging: !include common/default_logger.yaml
  logging: !include common/debug_logger.yaml
  wifi: !include common/wifi.yaml
  base_train_sounds: !include base_train_sounds.yaml
