substitutions:
  node_name: hatrainsounds
  friendly_name: "Home Assistant Train Sounds"
  area: Dev
  comment: "This is a version designed to connect to Home Assistant too"
  box_config_file_name: ha_train_sounds
  onboard_light_id: "atom_light"
  train_sounds_script_mode: restart
  # FIXME: make this dynamic
  first_train_sound_url: "https://www.soundjay.com/transportation/train-crossing-bell-01.mp3"
  second_train_sound_url: "https://www.soundjay.com/transportation/train-depart-with-whistle-01.mp3"
  third_train_sound_url: "https://www.soundjay.com/transportation/train-pass-by-with-whistle-01.mp3"
  fourth_train_sound_url: "https://www.soundjay.com/transportation/train-whistle-01.mp3"

packages:
  # logging: !include common/default_logger.yaml
  logging: !include common/debug_logger.yaml
  wifi: !include common/wifi.yaml
  base_train_sounds: !include base_train_sounds.yaml
  api: !include common/api.yaml
  status_sensor: !include common/status_sensor.yaml
  dashboard_import: !include common/default_dashboard_import.yaml
